### PR TITLE
Specify order IDs

### PR DESCRIPTION
**Pull request by devsjc**
# Pull Request

## Description

Add ORDER_IDS env var from secret to NWP Consumer.

### CODE REVIEW

**Comment by peterdudfield** [comment]
Would it possible to change to merge in 'development' branch? otherwise it looks good

**Comment by devsjc** [comment]
Changed branch to merge. What's the motivation behind having sepearate branches for development and production, as well as seperate folders within the tf repo?

**Comment by peterdudfield** [comment]
> Changed branch to merge form main to development. What's the motivation behind having sepearate branches for development and production, as well as seperate folders within the tf repo?

terraform cloud, can select a branch for which to pull it from. 

I guess it useful to have different folders so we can have different set up, without blocking the merge in to main, if we need to for a different reason. Note all the services terraform is not duplicated. So really it just one 'main.py' file for each env

**Comment by peterdudfield** [comment]
Dont worry about the local stack tests failing

**Comment by devsjc** [comment]
I guess what's confusing me is: if the development stack in terraform cloud always pulls from the development branch here, what's the benefit of having the production folder for tf present in the development branch? And similarly the vice-versa for prod?

Forgive me if you have explained it already in the above and I just haven't cottoned on yet!

**Pull request merged**
