### PR TITLE
Add pvsite rds database to rds module

### PR DESCRIPTION
**Pull request by devsjc**
# Pull Request

## Description

Creates RDS instance in module for PVSite postgres database

### CODE REVIEW

**Comment by peterdudfield** [comment]
Terraform looks good. 

I cant remeber what we decided, did we want to mix the NIA project (national and region) terraform code with the SBRI project (site level). I thought we should separate things, as it keeps things a bit more independent. We would have to pass a vpc_id (and maybe some subnet ids) as variables into this code. What do you think @devsjc

**Comment by devsjc** [comment]
Do you mean as in create a new module for this? `site-database` or something?

**Comment by peterdudfield** [comment]
> Do you mean as in create a new module for this? `site-database` or something? or keep the code with the rest of the database code but with variable subnet ids/vpc_ids?

Seperate code base. I.e you can heat `terraform destroy` and not worry about anything in NIA project breaking

**Comment by devsjc** [comment]
Ah I'm with you - new repo then?

**Pull request closed without merging**
